[package]
name = "generator"
description = "Deterministic tensor input generation for Psyduck benchmarks."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
tensor.workspace = true
thiserror.workspace = true
