[workspace.package]
authors = ["Alex Perkins"]
edition = "2024"
keywords = ["rust", "ml", "psyduck"]
publish = false
repository = "https://github.com/sashjdn/psyduck"
version = "0.1.0"

[workspace]
members = [
    "bin",
    "model",
    "tensor",
    "instrument",
    "instrument/macros",
]
resolver = "3"

[workspace.dependencies]
clap = { version = "4.5.60", features = ["derive"] }
convert_case = "0.8.0"
opentelemetry = "0.31.0"
opentelemetry-prometheus = { version = "0.31.0", features = ["prometheus-encoding"] }
opentelemetry_sdk = "0.31.0"
proc-macro-crate = "3.4.0"
proc-macro2 = "1.0.106"
prometheus = "0.14.0"
quote = "1.0.46"
syn = { version = "2.0.118", features = ["clone-impls", "extra-traits", "full", "parsing", "printing", "proc-macro"] }
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22" }

# local crates
tensor = { path = "tensor" }
model = { path = "model" }
instrument = { path = "instrument" }
instrument-macros = { path = "instrument/macros" }

[workspace.metadata.cargo-machete]
ignored = []

[profile.profiling]
inherits = "release"
debug = "line-tables-only"
split-debuginfo = "unpacked"
strip = "none"
