[package]
name = "kernel"
description = "CUDA kernel sources and entry-point metadata for Psyduck."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cudarc = { workspace = true, features = ["driver", "nvrtc", "cublas"] }
tensor.workspace = true
thiserror.workspace = true
tracing.workspace = true
