[package]
name = "instrument"
description = "OpenTelemetry and Prometheus measurement registry utilities for Psyduck."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
instrument-macros = { workspace = true, optional = true }
opentelemetry.workspace = true
opentelemetry-prometheus.workspace = true
opentelemetry_sdk.workspace = true
prometheus.workspace = true
thiserror.workspace = true

[dev-dependencies]
opentelemetry.workspace = true

[features]
default = ["macros"]
macros = ["dep:instrument-macros"]
